spring:
  mvc:
    pathmatch:
      #路径匹配策略使用 更换匹配策略
      matching-strategy: ant_path_matcher
  application:
    name: ToLearn
  profiles:
    active: dev
  #数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/to_learn?serverTimezone=Asia/Shanghai
    username: root
    password: 123456
  #session失效时间
  session:
    timeout: 86400
    store-type: redis
  #Redis&Redisson配置
  redis:
    host: localhost
    port: 6379
    database: 0
  jackson:
    time-zone: GMT+8
    date-format: java.text.SimpleDateFormat
  #邮箱配置，为用户接收验证码的邮箱
  mail:
    host: host
    username: username
    password: password
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB

server:
  port: 8080
  #应用上下文
  servlet:
    context-path: /api
    session:
      cookie:
        domain: localhost
        http-only: false

mybatis-plus:
  configuration:
    #将驼峰转为下划线
    map-underscore-to-camel-case: on
    #打印日志信息
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      logic-delete-field: isDelete #全局逻辑删除的实体字段名(since 3.3.0,配置后可以忽略不配置步骤2)
      logic-delete-value: 1        #逻辑已删除值(默认为 1)
      logic-not-delete-value: 0    #逻辑未删除值(默认为 0)
      id-type: auto

#接口文档
knife4j:
  enable: true
  openapi:
    title: ToLearn接口文档
    description: "ToLearn用户匹配系统"
    email: 1693717911@qq.com
    version: v4.0
    license: Apache 2.0
    concat: BraumAce
    group:
      ToLearn:
        group-name: ToLearn
        api-rule: package
        api-rule-resources:
          - com.tolearn

ToLearn:
  #图片临时目录
  img: /img/
  #定时任务
  job: "0 0 0 * * ? *"
  #布隆过滤器解决缓存穿透
  enable-bloom-filter: false
  #默认使用本地存储
  use-local-storage: true